-- filmorate."user" definition

-- Drop table

-- DROP TABLE filmorate."user";

CREATE TABLE filmorate."user" (
	user_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- Уникальный идентификатор пользователя
	email varchar(50) NOT NULL, -- Адрес электронной почты
	login varchar(50) NOT NULL, -- Логин пользователя
	"name" varchar(150) NOT NULL, -- Имя пользователя
	birthday date NOT NULL, -- Дата рождения
	CONSTRAINT user_email_uk UNIQUE (email),
	CONSTRAINT user_login_uk UNIQUE (login),
	CONSTRAINT user_pk PRIMARY KEY (user_id)
);
COMMENT ON TABLE filmorate."user" IS 'Пользователи';

-- Column comments

COMMENT ON COLUMN filmorate."user".user_id IS 'Уникальный идентификатор пользователя';
COMMENT ON COLUMN filmorate."user".email IS 'Адрес электронной почты';
COMMENT ON COLUMN filmorate."user".login IS 'Логин пользователя';
COMMENT ON COLUMN filmorate."user"."name" IS 'Имя пользователя';
COMMENT ON COLUMN filmorate."user".birthday IS 'Дата рождения';


-- filmorate.film definition

-- Drop table

-- DROP TABLE filmorate.film;

CREATE TABLE filmorate.film (
	film_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- Уникальный идентификатор фильма
	"name" varchar(150) NOT NULL, -- Название фильма
	description varchar(200) NULL, -- Описание фильма
	releasedate date NOT NULL, -- Дата релиза
	duration int4 NOT NULL, -- Продолжительность фильма
	rating int4 NOT NULL DEFAULT 0, -- Рейтинг
	CONSTRAINT film_name_release_date_uk UNIQUE (name, releasedate),
	CONSTRAINT film_pk PRIMARY KEY (film_id)
);
COMMENT ON TABLE filmorate.film IS 'Фильмы';

-- Column comments

COMMENT ON COLUMN filmorate.film.film_id IS 'Уникальный идентификатор фильма';
COMMENT ON COLUMN filmorate.film."name" IS 'Название фильма';
COMMENT ON COLUMN filmorate.film.description IS 'Описание фильма';
COMMENT ON COLUMN filmorate.film.releasedate IS 'Дата релиза';
COMMENT ON COLUMN filmorate.film.duration IS 'Продолжительность фильма';
COMMENT ON COLUMN filmorate.film.rating IS 'Рейтинг';


-- filmorate.likes definition

-- Drop table

-- DROP TABLE filmorate.likes;

CREATE TABLE filmorate.likes (
	likes_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- Уникальный идентификатор
	film_id int4 NOT NULL, -- Идентификатор фильма
	user_id int4 NOT NULL, -- Идентификатор пользователя
	CONSTRAINT likes_pk PRIMARY KEY (likes_id),
	CONSTRAINT likes_film_fk FOREIGN KEY (film_id) REFERENCES filmorate.film(film_id),
	CONSTRAINT likes_user_fk FOREIGN KEY (user_id) REFERENCES filmorate."user"(user_id)
);
COMMENT ON TABLE filmorate.likes IS 'Лайки';

-- Column comments

COMMENT ON COLUMN filmorate.likes.likes_id IS 'Уникальный идентификатор';
COMMENT ON COLUMN filmorate.likes.film_id IS 'Идентификатор фильма';
COMMENT ON COLUMN filmorate.likes.user_id IS 'Идентификатор пользователя';


-- filmorate.friends definition

-- Drop table

-- DROP TABLE filmorate.friends;

CREATE TABLE filmorate.friends (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- Уникальный идентификатор
	user_id int4 NOT NULL, -- Пользователь
	friend_id int4 NOT NULL, -- Друг
	CONSTRAINT friends_pk PRIMARY KEY (id),
	CONSTRAINT friends_friend_fk FOREIGN KEY (friend_id) REFERENCES filmorate."user"(user_id),
	CONSTRAINT friends_user_fk FOREIGN KEY (user_id) REFERENCES filmorate."user"(user_id)
);
COMMENT ON TABLE filmorate.friends IS 'Друзья';

-- Column comments

COMMENT ON COLUMN filmorate.friends.id IS 'Уникальный идентификатор';
COMMENT ON COLUMN filmorate.friends.user_id IS 'Пользователь';
COMMENT ON COLUMN filmorate.friends.friend_id IS 'Друг';